name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
     permissions:
      contents: write # Questo concede i permessi di scrittura ai contenuti del repository
      pages: write    # Se stai usando GitHub Pages per deployment
      id-token: write # Se stai usando OIDC per deploy su servizi cloud esterni
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Usa la versione del tuo progetto

      - name: Publish app
        run: dotnet publish -c Release -o release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
